// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cmd.proto

package sg.edu.sutd.dss.protocol;

public final class SnodeProtoc {
  private SnodeProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StoreRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string userId = 1;
    boolean hasUserId();
    String getUserId();
    
    // required .sg.sutd.dss.protocol.StoreRequest.EncBlockDesc encBlockDesc = 2;
    boolean hasEncBlockDesc();
    sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc getEncBlockDesc();
    sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDescOrBuilder getEncBlockDescOrBuilder();
    
    // optional int32 reqSn = 3;
    boolean hasReqSn();
    int getReqSn();
  }
  public static final class StoreRequest extends
      com.google.protobuf.GeneratedMessage
      implements StoreRequestOrBuilder {
    // Use StoreRequest.newBuilder() to construct.
    private StoreRequest(Builder builder) {
      super(builder);
    }
    private StoreRequest(boolean noInit) {}
    
    private static final StoreRequest defaultInstance;
    public static StoreRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public StoreRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sg.edu.sutd.dss.protocol.SnodeProtoc.internal_static_sg_sutd_dss_protocol_StoreRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sg.edu.sutd.dss.protocol.SnodeProtoc.internal_static_sg_sutd_dss_protocol_StoreRequest_fieldAccessorTable;
    }
    
    public interface EncBlockDescOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string encBlockId = 1;
      boolean hasEncBlockId();
      String getEncBlockId();
      
      // optional string path = 2;
      boolean hasPath();
      String getPath();
      
      // required int32 size = 3;
      boolean hasSize();
      int getSize();
    }
    public static final class EncBlockDesc extends
        com.google.protobuf.GeneratedMessage
        implements EncBlockDescOrBuilder {
      // Use EncBlockDesc.newBuilder() to construct.
      private EncBlockDesc(Builder builder) {
        super(builder);
      }
      private EncBlockDesc(boolean noInit) {}
      
      private static final EncBlockDesc defaultInstance;
      public static EncBlockDesc getDefaultInstance() {
        return defaultInstance;
      }
      
      public EncBlockDesc getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sg.edu.sutd.dss.protocol.SnodeProtoc.internal_static_sg_sutd_dss_protocol_StoreRequest_EncBlockDesc_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sg.edu.sutd.dss.protocol.SnodeProtoc.internal_static_sg_sutd_dss_protocol_StoreRequest_EncBlockDesc_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string encBlockId = 1;
      public static final int ENCBLOCKID_FIELD_NUMBER = 1;
      private java.lang.Object encBlockId_;
      public boolean hasEncBlockId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getEncBlockId() {
        java.lang.Object ref = encBlockId_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            encBlockId_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getEncBlockIdBytes() {
        java.lang.Object ref = encBlockId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          encBlockId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional string path = 2;
      public static final int PATH_FIELD_NUMBER = 2;
      private java.lang.Object path_;
      public boolean hasPath() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPath() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            path_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required int32 size = 3;
      public static final int SIZE_FIELD_NUMBER = 3;
      private int size_;
      public boolean hasSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getSize() {
        return size_;
      }
      
      private void initFields() {
        encBlockId_ = "";
        path_ = "";
        size_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasEncBlockId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasSize()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getEncBlockIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getPathBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, size_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getEncBlockIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getPathBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, size_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDescOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return sg.edu.sutd.dss.protocol.SnodeProtoc.internal_static_sg_sutd_dss_protocol_StoreRequest_EncBlockDesc_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return sg.edu.sutd.dss.protocol.SnodeProtoc.internal_static_sg_sutd_dss_protocol_StoreRequest_EncBlockDesc_fieldAccessorTable;
        }
        
        // Construct using sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          encBlockId_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          path_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          size_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.getDescriptor();
        }
        
        public sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc getDefaultInstanceForType() {
          return sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.getDefaultInstance();
        }
        
        public sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc build() {
          sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc buildPartial() {
          sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc result = new sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.encBlockId_ = encBlockId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.path_ = path_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.size_ = size_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc) {
            return mergeFrom((sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc other) {
          if (other == sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.getDefaultInstance()) return this;
          if (other.hasEncBlockId()) {
            setEncBlockId(other.getEncBlockId());
          }
          if (other.hasPath()) {
            setPath(other.getPath());
          }
          if (other.hasSize()) {
            setSize(other.getSize());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasEncBlockId()) {
            
            return false;
          }
          if (!hasSize()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                encBlockId_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                path_ = input.readBytes();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                size_ = input.readInt32();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string encBlockId = 1;
        private java.lang.Object encBlockId_ = "";
        public boolean hasEncBlockId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getEncBlockId() {
          java.lang.Object ref = encBlockId_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            encBlockId_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setEncBlockId(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          encBlockId_ = value;
          onChanged();
          return this;
        }
        public Builder clearEncBlockId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          encBlockId_ = getDefaultInstance().getEncBlockId();
          onChanged();
          return this;
        }
        void setEncBlockId(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          encBlockId_ = value;
          onChanged();
        }
        
        // optional string path = 2;
        private java.lang.Object path_ = "";
        public boolean hasPath() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getPath() {
          java.lang.Object ref = path_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            path_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setPath(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          path_ = value;
          onChanged();
          return this;
        }
        public Builder clearPath() {
          bitField0_ = (bitField0_ & ~0x00000002);
          path_ = getDefaultInstance().getPath();
          onChanged();
          return this;
        }
        void setPath(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          path_ = value;
          onChanged();
        }
        
        // required int32 size = 3;
        private int size_ ;
        public boolean hasSize() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public int getSize() {
          return size_;
        }
        public Builder setSize(int value) {
          bitField0_ |= 0x00000004;
          size_ = value;
          onChanged();
          return this;
        }
        public Builder clearSize() {
          bitField0_ = (bitField0_ & ~0x00000004);
          size_ = 0;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:sg.sutd.dss.protocol.StoreRequest.EncBlockDesc)
      }
      
      static {
        defaultInstance = new EncBlockDesc(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:sg.sutd.dss.protocol.StoreRequest.EncBlockDesc)
    }
    
    private int bitField0_;
    // required string userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .sg.sutd.dss.protocol.StoreRequest.EncBlockDesc encBlockDesc = 2;
    public static final int ENCBLOCKDESC_FIELD_NUMBER = 2;
    private sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc encBlockDesc_;
    public boolean hasEncBlockDesc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc getEncBlockDesc() {
      return encBlockDesc_;
    }
    public sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDescOrBuilder getEncBlockDescOrBuilder() {
      return encBlockDesc_;
    }
    
    // optional int32 reqSn = 3;
    public static final int REQSN_FIELD_NUMBER = 3;
    private int reqSn_;
    public boolean hasReqSn() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getReqSn() {
      return reqSn_;
    }
    
    private void initFields() {
      userId_ = "";
      encBlockDesc_ = sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.getDefaultInstance();
      reqSn_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEncBlockDesc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getEncBlockDesc().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, encBlockDesc_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, reqSn_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, encBlockDesc_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, reqSn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sg.edu.sutd.dss.protocol.SnodeProtoc.internal_static_sg_sutd_dss_protocol_StoreRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sg.edu.sutd.dss.protocol.SnodeProtoc.internal_static_sg_sutd_dss_protocol_StoreRequest_fieldAccessorTable;
      }
      
      // Construct using sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEncBlockDescFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (encBlockDescBuilder_ == null) {
          encBlockDesc_ = sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.getDefaultInstance();
        } else {
          encBlockDescBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        reqSn_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.getDescriptor();
      }
      
      public sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest getDefaultInstanceForType() {
        return sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.getDefaultInstance();
      }
      
      public sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest build() {
        sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest buildPartial() {
        sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest result = new sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (encBlockDescBuilder_ == null) {
          result.encBlockDesc_ = encBlockDesc_;
        } else {
          result.encBlockDesc_ = encBlockDescBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.reqSn_ = reqSn_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest) {
          return mergeFrom((sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest other) {
        if (other == sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasEncBlockDesc()) {
          mergeEncBlockDesc(other.getEncBlockDesc());
        }
        if (other.hasReqSn()) {
          setReqSn(other.getReqSn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasEncBlockDesc()) {
          
          return false;
        }
        if (!getEncBlockDesc().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userId_ = input.readBytes();
              break;
            }
            case 18: {
              sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.Builder subBuilder = sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.newBuilder();
              if (hasEncBlockDesc()) {
                subBuilder.mergeFrom(getEncBlockDesc());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setEncBlockDesc(subBuilder.buildPartial());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              reqSn_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string userId = 1;
      private java.lang.Object userId_ = "";
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      void setUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
      }
      
      // required .sg.sutd.dss.protocol.StoreRequest.EncBlockDesc encBlockDesc = 2;
      private sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc encBlockDesc_ = sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc, sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.Builder, sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDescOrBuilder> encBlockDescBuilder_;
      public boolean hasEncBlockDesc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc getEncBlockDesc() {
        if (encBlockDescBuilder_ == null) {
          return encBlockDesc_;
        } else {
          return encBlockDescBuilder_.getMessage();
        }
      }
      public Builder setEncBlockDesc(sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc value) {
        if (encBlockDescBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          encBlockDesc_ = value;
          onChanged();
        } else {
          encBlockDescBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setEncBlockDesc(
          sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.Builder builderForValue) {
        if (encBlockDescBuilder_ == null) {
          encBlockDesc_ = builderForValue.build();
          onChanged();
        } else {
          encBlockDescBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeEncBlockDesc(sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc value) {
        if (encBlockDescBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              encBlockDesc_ != sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.getDefaultInstance()) {
            encBlockDesc_ =
              sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.newBuilder(encBlockDesc_).mergeFrom(value).buildPartial();
          } else {
            encBlockDesc_ = value;
          }
          onChanged();
        } else {
          encBlockDescBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearEncBlockDesc() {
        if (encBlockDescBuilder_ == null) {
          encBlockDesc_ = sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.getDefaultInstance();
          onChanged();
        } else {
          encBlockDescBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.Builder getEncBlockDescBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getEncBlockDescFieldBuilder().getBuilder();
      }
      public sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDescOrBuilder getEncBlockDescOrBuilder() {
        if (encBlockDescBuilder_ != null) {
          return encBlockDescBuilder_.getMessageOrBuilder();
        } else {
          return encBlockDesc_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc, sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.Builder, sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDescOrBuilder> 
          getEncBlockDescFieldBuilder() {
        if (encBlockDescBuilder_ == null) {
          encBlockDescBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc, sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.Builder, sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDescOrBuilder>(
                  encBlockDesc_,
                  getParentForChildren(),
                  isClean());
          encBlockDesc_ = null;
        }
        return encBlockDescBuilder_;
      }
      
      // optional int32 reqSn = 3;
      private int reqSn_ ;
      public boolean hasReqSn() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getReqSn() {
        return reqSn_;
      }
      public Builder setReqSn(int value) {
        bitField0_ |= 0x00000004;
        reqSn_ = value;
        onChanged();
        return this;
      }
      public Builder clearReqSn() {
        bitField0_ = (bitField0_ & ~0x00000004);
        reqSn_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:sg.sutd.dss.protocol.StoreRequest)
    }
    
    static {
      defaultInstance = new StoreRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sg.sutd.dss.protocol.StoreRequest)
  }
  
  public interface StoreAckOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bool isApproved = 1;
    boolean hasIsApproved();
    boolean getIsApproved();
    
    // optional bool isDone = 2;
    boolean hasIsDone();
    boolean getIsDone();
    
    // optional int32 reqSn = 3;
    boolean hasReqSn();
    int getReqSn();
  }
  public static final class StoreAck extends
      com.google.protobuf.GeneratedMessage
      implements StoreAckOrBuilder {
    // Use StoreAck.newBuilder() to construct.
    private StoreAck(Builder builder) {
      super(builder);
    }
    private StoreAck(boolean noInit) {}
    
    private static final StoreAck defaultInstance;
    public static StoreAck getDefaultInstance() {
      return defaultInstance;
    }
    
    public StoreAck getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sg.edu.sutd.dss.protocol.SnodeProtoc.internal_static_sg_sutd_dss_protocol_StoreAck_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sg.edu.sutd.dss.protocol.SnodeProtoc.internal_static_sg_sutd_dss_protocol_StoreAck_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bool isApproved = 1;
    public static final int ISAPPROVED_FIELD_NUMBER = 1;
    private boolean isApproved_;
    public boolean hasIsApproved() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getIsApproved() {
      return isApproved_;
    }
    
    // optional bool isDone = 2;
    public static final int ISDONE_FIELD_NUMBER = 2;
    private boolean isDone_;
    public boolean hasIsDone() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getIsDone() {
      return isDone_;
    }
    
    // optional int32 reqSn = 3;
    public static final int REQSN_FIELD_NUMBER = 3;
    private int reqSn_;
    public boolean hasReqSn() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getReqSn() {
      return reqSn_;
    }
    
    private void initFields() {
      isApproved_ = false;
      isDone_ = false;
      reqSn_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isApproved_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isDone_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, reqSn_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isApproved_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isDone_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, reqSn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sg.edu.sutd.dss.protocol.SnodeProtoc.internal_static_sg_sutd_dss_protocol_StoreAck_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sg.edu.sutd.dss.protocol.SnodeProtoc.internal_static_sg_sutd_dss_protocol_StoreAck_fieldAccessorTable;
      }
      
      // Construct using sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        isApproved_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        isDone_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        reqSn_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck.getDescriptor();
      }
      
      public sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck getDefaultInstanceForType() {
        return sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck.getDefaultInstance();
      }
      
      public sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck build() {
        sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck buildPartial() {
        sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck result = new sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isApproved_ = isApproved_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isDone_ = isDone_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.reqSn_ = reqSn_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck) {
          return mergeFrom((sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck other) {
        if (other == sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck.getDefaultInstance()) return this;
        if (other.hasIsApproved()) {
          setIsApproved(other.getIsApproved());
        }
        if (other.hasIsDone()) {
          setIsDone(other.getIsDone());
        }
        if (other.hasReqSn()) {
          setReqSn(other.getReqSn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isApproved_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isDone_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              reqSn_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bool isApproved = 1;
      private boolean isApproved_ ;
      public boolean hasIsApproved() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getIsApproved() {
        return isApproved_;
      }
      public Builder setIsApproved(boolean value) {
        bitField0_ |= 0x00000001;
        isApproved_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsApproved() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isApproved_ = false;
        onChanged();
        return this;
      }
      
      // optional bool isDone = 2;
      private boolean isDone_ ;
      public boolean hasIsDone() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getIsDone() {
        return isDone_;
      }
      public Builder setIsDone(boolean value) {
        bitField0_ |= 0x00000002;
        isDone_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsDone() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isDone_ = false;
        onChanged();
        return this;
      }
      
      // optional int32 reqSn = 3;
      private int reqSn_ ;
      public boolean hasReqSn() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getReqSn() {
        return reqSn_;
      }
      public Builder setReqSn(int value) {
        bitField0_ |= 0x00000004;
        reqSn_ = value;
        onChanged();
        return this;
      }
      public Builder clearReqSn() {
        bitField0_ = (bitField0_ & ~0x00000004);
        reqSn_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:sg.sutd.dss.protocol.StoreAck)
    }
    
    static {
      defaultInstance = new StoreAck(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sg.sutd.dss.protocol.StoreAck)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sg_sutd_dss_protocol_StoreRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sg_sutd_dss_protocol_StoreRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sg_sutd_dss_protocol_StoreRequest_EncBlockDesc_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sg_sutd_dss_protocol_StoreRequest_EncBlockDesc_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sg_sutd_dss_protocol_StoreAck_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sg_sutd_dss_protocol_StoreAck_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tCmd.proto\022\024sg.sutd.dss.protocol\"\264\001\n\014St" +
      "oreRequest\022\016\n\006userId\030\001 \002(\t\022E\n\014encBlockDe" +
      "sc\030\002 \002(\0132/.sg.sutd.dss.protocol.StoreReq" +
      "uest.EncBlockDesc\022\r\n\005reqSn\030\003 \001(\005\032>\n\014EncB" +
      "lockDesc\022\022\n\nencBlockId\030\001 \002(\t\022\014\n\004path\030\002 \001" +
      "(\t\022\014\n\004size\030\003 \002(\005\"=\n\010StoreAck\022\022\n\nisApprov" +
      "ed\030\001 \001(\010\022\016\n\006isDone\030\002 \001(\010\022\r\n\005reqSn\030\003 \001(\005B" +
      "\'\n\030sg.edu.sutd.dss.protocolB\013SnodeProtoc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sg_sutd_dss_protocol_StoreRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sg_sutd_dss_protocol_StoreRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sg_sutd_dss_protocol_StoreRequest_descriptor,
              new java.lang.String[] { "UserId", "EncBlockDesc", "ReqSn", },
              sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.class,
              sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.Builder.class);
          internal_static_sg_sutd_dss_protocol_StoreRequest_EncBlockDesc_descriptor =
            internal_static_sg_sutd_dss_protocol_StoreRequest_descriptor.getNestedTypes().get(0);
          internal_static_sg_sutd_dss_protocol_StoreRequest_EncBlockDesc_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sg_sutd_dss_protocol_StoreRequest_EncBlockDesc_descriptor,
              new java.lang.String[] { "EncBlockId", "Path", "Size", },
              sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.class,
              sg.edu.sutd.dss.protocol.SnodeProtoc.StoreRequest.EncBlockDesc.Builder.class);
          internal_static_sg_sutd_dss_protocol_StoreAck_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_sg_sutd_dss_protocol_StoreAck_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sg_sutd_dss_protocol_StoreAck_descriptor,
              new java.lang.String[] { "IsApproved", "IsDone", "ReqSn", },
              sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck.class,
              sg.edu.sutd.dss.protocol.SnodeProtoc.StoreAck.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
