// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CmdProtocol.proto

package sg.edu.sutd.dss.protocol.cmd;

public final class CmdProtocol {
  private CmdProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CmdOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required int32 id = 2;
    boolean hasId();
    int getId();
    
    // optional string dbgString = 3;
    boolean hasDbgString();
    String getDbgString();
    
    // required .sg.sutd.dss.protocol.cmd.Cmd.CmdType type = 4;
    boolean hasType();
    sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.CmdType getType();
  }
  public static final class Cmd extends
      com.google.protobuf.GeneratedMessage
      implements CmdOrBuilder {
    // Use Cmd.newBuilder() to construct.
    private Cmd(Builder builder) {
      super(builder);
    }
    private Cmd(boolean noInit) {}
    
    private static final Cmd defaultInstance;
    public static Cmd getDefaultInstance() {
      return defaultInstance;
    }
    
    public Cmd getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.internal_static_sg_sutd_dss_protocol_cmd_Cmd_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.internal_static_sg_sutd_dss_protocol_cmd_Cmd_fieldAccessorTable;
    }
    
    public enum CmdType
        implements com.google.protobuf.ProtocolMessageEnum {
      STORAGE(0, 0),
      CONTROL(1, 1),
      HEARTBEAT(2, 2),
      ;
      
      public static final int STORAGE_VALUE = 0;
      public static final int CONTROL_VALUE = 1;
      public static final int HEARTBEAT_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static CmdType valueOf(int value) {
        switch (value) {
          case 0: return STORAGE;
          case 1: return CONTROL;
          case 2: return HEARTBEAT;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<CmdType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CmdType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CmdType>() {
              public CmdType findValueByNumber(int number) {
                return CmdType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final CmdType[] VALUES = {
        STORAGE, CONTROL, HEARTBEAT, 
      };
      
      public static CmdType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private CmdType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:sg.sutd.dss.protocol.cmd.Cmd.CmdType)
    }
    
    public interface ArgumentOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // optional string aString = 1;
      boolean hasAString();
      String getAString();
      
      // optional int32 aInt32 = 2 [default = 0];
      boolean hasAInt32();
      int getAInt32();
    }
    public static final class Argument extends
        com.google.protobuf.GeneratedMessage
        implements ArgumentOrBuilder {
      // Use Argument.newBuilder() to construct.
      private Argument(Builder builder) {
        super(builder);
      }
      private Argument(boolean noInit) {}
      
      private static final Argument defaultInstance;
      public static Argument getDefaultInstance() {
        return defaultInstance;
      }
      
      public Argument getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.internal_static_sg_sutd_dss_protocol_cmd_Cmd_Argument_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.internal_static_sg_sutd_dss_protocol_cmd_Cmd_Argument_fieldAccessorTable;
      }
      
      private int bitField0_;
      // optional string aString = 1;
      public static final int ASTRING_FIELD_NUMBER = 1;
      private java.lang.Object aString_;
      public boolean hasAString() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getAString() {
        java.lang.Object ref = aString_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            aString_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getAStringBytes() {
        java.lang.Object ref = aString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          aString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional int32 aInt32 = 2 [default = 0];
      public static final int AINT32_FIELD_NUMBER = 2;
      private int aInt32_;
      public boolean hasAInt32() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getAInt32() {
        return aInt32_;
      }
      
      private void initFields() {
        aString_ = "";
        aInt32_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getAStringBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, aInt32_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getAStringBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, aInt32_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.ArgumentOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.internal_static_sg_sutd_dss_protocol_cmd_Cmd_Argument_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.internal_static_sg_sutd_dss_protocol_cmd_Cmd_Argument_fieldAccessorTable;
        }
        
        // Construct using sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          aString_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          aInt32_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument.getDescriptor();
        }
        
        public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument getDefaultInstanceForType() {
          return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument.getDefaultInstance();
        }
        
        public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument build() {
          sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument buildPartial() {
          sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument result = new sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.aString_ = aString_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.aInt32_ = aInt32_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument) {
            return mergeFrom((sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument other) {
          if (other == sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument.getDefaultInstance()) return this;
          if (other.hasAString()) {
            setAString(other.getAString());
          }
          if (other.hasAInt32()) {
            setAInt32(other.getAInt32());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                aString_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                aInt32_ = input.readInt32();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // optional string aString = 1;
        private java.lang.Object aString_ = "";
        public boolean hasAString() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getAString() {
          java.lang.Object ref = aString_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            aString_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setAString(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          aString_ = value;
          onChanged();
          return this;
        }
        public Builder clearAString() {
          bitField0_ = (bitField0_ & ~0x00000001);
          aString_ = getDefaultInstance().getAString();
          onChanged();
          return this;
        }
        void setAString(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          aString_ = value;
          onChanged();
        }
        
        // optional int32 aInt32 = 2 [default = 0];
        private int aInt32_ ;
        public boolean hasAInt32() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public int getAInt32() {
          return aInt32_;
        }
        public Builder setAInt32(int value) {
          bitField0_ |= 0x00000002;
          aInt32_ = value;
          onChanged();
          return this;
        }
        public Builder clearAInt32() {
          bitField0_ = (bitField0_ & ~0x00000002);
          aInt32_ = 0;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:sg.sutd.dss.protocol.cmd.Cmd.Argument)
      }
      
      static {
        defaultInstance = new Argument(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:sg.sutd.dss.protocol.cmd.Cmd.Argument)
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getId() {
      return id_;
    }
    
    // optional string dbgString = 3;
    public static final int DBGSTRING_FIELD_NUMBER = 3;
    private java.lang.Object dbgString_;
    public boolean hasDbgString() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDbgString() {
      java.lang.Object ref = dbgString_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          dbgString_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDbgStringBytes() {
      java.lang.Object ref = dbgString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        dbgString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .sg.sutd.dss.protocol.cmd.Cmd.CmdType type = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.CmdType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.CmdType getType() {
      return type_;
    }
    
    private void initFields() {
      name_ = "";
      id_ = 0;
      dbgString_ = "";
      type_ = sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.CmdType.STORAGE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDbgStringBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDbgStringBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.internal_static_sg_sutd_dss_protocol_cmd_Cmd_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.internal_static_sg_sutd_dss_protocol_cmd_Cmd_fieldAccessorTable;
      }
      
      // Construct using sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        dbgString_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.CmdType.STORAGE;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.getDescriptor();
      }
      
      public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd getDefaultInstanceForType() {
        return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.getDefaultInstance();
      }
      
      public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd build() {
        sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd buildPartial() {
        sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd result = new sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dbgString_ = dbgString_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd) {
          return mergeFrom((sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd other) {
        if (other == sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasDbgString()) {
          setDbgString(other.getDbgString());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              dbgString_ = input.readBytes();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.CmdType value = sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.CmdType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                type_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required int32 id = 2;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // optional string dbgString = 3;
      private java.lang.Object dbgString_ = "";
      public boolean hasDbgString() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDbgString() {
        java.lang.Object ref = dbgString_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          dbgString_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDbgString(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dbgString_ = value;
        onChanged();
        return this;
      }
      public Builder clearDbgString() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dbgString_ = getDefaultInstance().getDbgString();
        onChanged();
        return this;
      }
      void setDbgString(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        dbgString_ = value;
        onChanged();
      }
      
      // required .sg.sutd.dss.protocol.cmd.Cmd.CmdType type = 4;
      private sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.CmdType type_ = sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.CmdType.STORAGE;
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.CmdType getType() {
        return type_;
      }
      public Builder setType(sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.CmdType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.CmdType.STORAGE;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:sg.sutd.dss.protocol.cmd.Cmd)
    }
    
    static {
      defaultInstance = new Cmd(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sg.sutd.dss.protocol.cmd.Cmd)
  }
  
  public interface CmdListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .sg.sutd.dss.protocol.cmd.Cmd command = 1;
    java.util.List<sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd> 
        getCommandList();
    sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd getCommand(int index);
    int getCommandCount();
    java.util.List<? extends sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdOrBuilder> 
        getCommandOrBuilderList();
    sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdOrBuilder getCommandOrBuilder(
        int index);
  }
  public static final class CmdList extends
      com.google.protobuf.GeneratedMessage
      implements CmdListOrBuilder {
    // Use CmdList.newBuilder() to construct.
    private CmdList(Builder builder) {
      super(builder);
    }
    private CmdList(boolean noInit) {}
    
    private static final CmdList defaultInstance;
    public static CmdList getDefaultInstance() {
      return defaultInstance;
    }
    
    public CmdList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.internal_static_sg_sutd_dss_protocol_cmd_CmdList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.internal_static_sg_sutd_dss_protocol_cmd_CmdList_fieldAccessorTable;
    }
    
    // repeated .sg.sutd.dss.protocol.cmd.Cmd command = 1;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private java.util.List<sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd> command_;
    public java.util.List<sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd> getCommandList() {
      return command_;
    }
    public java.util.List<? extends sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdOrBuilder> 
        getCommandOrBuilderList() {
      return command_;
    }
    public int getCommandCount() {
      return command_.size();
    }
    public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd getCommand(int index) {
      return command_.get(index);
    }
    public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdOrBuilder getCommandOrBuilder(
        int index) {
      return command_.get(index);
    }
    
    private void initFields() {
      command_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getCommandCount(); i++) {
        if (!getCommand(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < command_.size(); i++) {
        output.writeMessage(1, command_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < command_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, command_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.internal_static_sg_sutd_dss_protocol_cmd_CmdList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.internal_static_sg_sutd_dss_protocol_cmd_CmdList_fieldAccessorTable;
      }
      
      // Construct using sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCommandFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (commandBuilder_ == null) {
          command_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          commandBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList.getDescriptor();
      }
      
      public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList getDefaultInstanceForType() {
        return sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList.getDefaultInstance();
      }
      
      public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList build() {
        sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList buildPartial() {
        sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList result = new sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList(this);
        int from_bitField0_ = bitField0_;
        if (commandBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            command_ = java.util.Collections.unmodifiableList(command_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.command_ = command_;
        } else {
          result.command_ = commandBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList) {
          return mergeFrom((sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList other) {
        if (other == sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList.getDefaultInstance()) return this;
        if (commandBuilder_ == null) {
          if (!other.command_.isEmpty()) {
            if (command_.isEmpty()) {
              command_ = other.command_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCommandIsMutable();
              command_.addAll(other.command_);
            }
            onChanged();
          }
        } else {
          if (!other.command_.isEmpty()) {
            if (commandBuilder_.isEmpty()) {
              commandBuilder_.dispose();
              commandBuilder_ = null;
              command_ = other.command_;
              bitField0_ = (bitField0_ & ~0x00000001);
              commandBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCommandFieldBuilder() : null;
            } else {
              commandBuilder_.addAllMessages(other.command_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getCommandCount(); i++) {
          if (!getCommand(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Builder subBuilder = sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addCommand(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .sg.sutd.dss.protocol.cmd.Cmd command = 1;
      private java.util.List<sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd> command_ =
        java.util.Collections.emptyList();
      private void ensureCommandIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          command_ = new java.util.ArrayList<sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd>(command_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd, sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Builder, sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdOrBuilder> commandBuilder_;
      
      public java.util.List<sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd> getCommandList() {
        if (commandBuilder_ == null) {
          return java.util.Collections.unmodifiableList(command_);
        } else {
          return commandBuilder_.getMessageList();
        }
      }
      public int getCommandCount() {
        if (commandBuilder_ == null) {
          return command_.size();
        } else {
          return commandBuilder_.getCount();
        }
      }
      public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd getCommand(int index) {
        if (commandBuilder_ == null) {
          return command_.get(index);
        } else {
          return commandBuilder_.getMessage(index);
        }
      }
      public Builder setCommand(
          int index, sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd value) {
        if (commandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommandIsMutable();
          command_.set(index, value);
          onChanged();
        } else {
          commandBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setCommand(
          int index, sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Builder builderForValue) {
        if (commandBuilder_ == null) {
          ensureCommandIsMutable();
          command_.set(index, builderForValue.build());
          onChanged();
        } else {
          commandBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addCommand(sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd value) {
        if (commandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommandIsMutable();
          command_.add(value);
          onChanged();
        } else {
          commandBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addCommand(
          int index, sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd value) {
        if (commandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommandIsMutable();
          command_.add(index, value);
          onChanged();
        } else {
          commandBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addCommand(
          sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Builder builderForValue) {
        if (commandBuilder_ == null) {
          ensureCommandIsMutable();
          command_.add(builderForValue.build());
          onChanged();
        } else {
          commandBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addCommand(
          int index, sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Builder builderForValue) {
        if (commandBuilder_ == null) {
          ensureCommandIsMutable();
          command_.add(index, builderForValue.build());
          onChanged();
        } else {
          commandBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllCommand(
          java.lang.Iterable<? extends sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd> values) {
        if (commandBuilder_ == null) {
          ensureCommandIsMutable();
          super.addAll(values, command_);
          onChanged();
        } else {
          commandBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearCommand() {
        if (commandBuilder_ == null) {
          command_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          commandBuilder_.clear();
        }
        return this;
      }
      public Builder removeCommand(int index) {
        if (commandBuilder_ == null) {
          ensureCommandIsMutable();
          command_.remove(index);
          onChanged();
        } else {
          commandBuilder_.remove(index);
        }
        return this;
      }
      public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Builder getCommandBuilder(
          int index) {
        return getCommandFieldBuilder().getBuilder(index);
      }
      public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdOrBuilder getCommandOrBuilder(
          int index) {
        if (commandBuilder_ == null) {
          return command_.get(index);  } else {
          return commandBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdOrBuilder> 
           getCommandOrBuilderList() {
        if (commandBuilder_ != null) {
          return commandBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(command_);
        }
      }
      public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Builder addCommandBuilder() {
        return getCommandFieldBuilder().addBuilder(
            sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.getDefaultInstance());
      }
      public sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Builder addCommandBuilder(
          int index) {
        return getCommandFieldBuilder().addBuilder(
            index, sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.getDefaultInstance());
      }
      public java.util.List<sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Builder> 
           getCommandBuilderList() {
        return getCommandFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd, sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Builder, sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdOrBuilder> 
          getCommandFieldBuilder() {
        if (commandBuilder_ == null) {
          commandBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd, sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Builder, sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdOrBuilder>(
                  command_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          command_ = null;
        }
        return commandBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:sg.sutd.dss.protocol.cmd.CmdList)
    }
    
    static {
      defaultInstance = new CmdList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sg.sutd.dss.protocol.cmd.CmdList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sg_sutd_dss_protocol_cmd_Cmd_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sg_sutd_dss_protocol_cmd_Cmd_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sg_sutd_dss_protocol_cmd_Cmd_Argument_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sg_sutd_dss_protocol_cmd_Cmd_Argument_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sg_sutd_dss_protocol_cmd_CmdList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sg_sutd_dss_protocol_cmd_CmdList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CmdProtocol.proto\022\030sg.sutd.dss.protoco" +
      "l.cmd\"\313\001\n\003Cmd\022\014\n\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022" +
      "\021\n\tdbgString\030\003 \001(\t\0223\n\004type\030\004 \002(\0162%.sg.su" +
      "td.dss.protocol.cmd.Cmd.CmdType\032.\n\010Argum" +
      "ent\022\017\n\007aString\030\001 \001(\t\022\021\n\006aInt32\030\002 \001(\005:\0010\"" +
      "2\n\007CmdType\022\013\n\007STORAGE\020\000\022\013\n\007CONTROL\020\001\022\r\n\t" +
      "HEARTBEAT\020\002\"9\n\007CmdList\022.\n\007command\030\001 \003(\0132" +
      "\035.sg.sutd.dss.protocol.cmd.CmdB+\n\034sg.edu" +
      ".sutd.dss.protocol.cmdB\013CmdProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sg_sutd_dss_protocol_cmd_Cmd_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sg_sutd_dss_protocol_cmd_Cmd_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sg_sutd_dss_protocol_cmd_Cmd_descriptor,
              new java.lang.String[] { "Name", "Id", "DbgString", "Type", },
              sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.class,
              sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Builder.class);
          internal_static_sg_sutd_dss_protocol_cmd_Cmd_Argument_descriptor =
            internal_static_sg_sutd_dss_protocol_cmd_Cmd_descriptor.getNestedTypes().get(0);
          internal_static_sg_sutd_dss_protocol_cmd_Cmd_Argument_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sg_sutd_dss_protocol_cmd_Cmd_Argument_descriptor,
              new java.lang.String[] { "AString", "AInt32", },
              sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument.class,
              sg.edu.sutd.dss.protocol.cmd.CmdProtocol.Cmd.Argument.Builder.class);
          internal_static_sg_sutd_dss_protocol_cmd_CmdList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_sg_sutd_dss_protocol_cmd_CmdList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sg_sutd_dss_protocol_cmd_CmdList_descriptor,
              new java.lang.String[] { "Command", },
              sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList.class,
              sg.edu.sutd.dss.protocol.cmd.CmdProtocol.CmdList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
